
title: Rowe Innovations, LLC
email: james@roweinnovations.com 
description: >- # this means to ignore newlines until "baseurl:"
  (c) 2024 Rowe Innovations, LLC. 
  All rights reserved.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.roweinnovations.com" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  jsr6720
linkedin_username: jsr6720

# index.html to get it to work with cloudfront static pages
permalink: /:title/index.html 

# using collections to separate the lines of business
collections:
  software: # published apps
    output: true
    permalink: /:collection/:name/index.html
  books: # published books
    output: true
    permalink: /:collection/:name/index.html

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
